apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-2
  name: my-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/my-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
